/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 23-May-2014 00:20:44
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
    14993,      0,      0 
  },
  {
    32767, -32768,  32767 
  },
  {
    14993,      0,      0 
  },
  {
    32767,  32767,  32767 
  },
  {
    18321,      0,      0 
  },
  {
    32767, -32768,  32767 
  },
  {
    18321,      0,      0 
  },
  {
    32767,  32767,  32767 
  },
  {
    26216,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    32767,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    32767,      0,      0 
  },
  {
    32767,  32767,  30588 
  },
  {
    32767,      0,      0 
  },
  {
    32767, -32768,  30402 
  },
  {
    32767,      0,      0 
  },
  {
    32767,  32767,  23893 
  },
  {
    32767,      0,      0 
  },
  {
    32767, -31069,  23354 
  },
  {
    32767,      0,      0 
  },
  {
    32767,   2803,  15700 
  },
  {
    32767,      0,      0 
  }
};
